#!/bin/bash

# Some constants for use
COLOR_RED='\033[31m'
COLOR_GREEN='\033[32m'
COLOR_BG_GREEN='\033[42m'
COLOR_YELLOW='\033[33m'
COLOR_NORMAL='\033[0m'

# Useful one-liner to get the full dir name of the current script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# This file holds the references to usernames, hostnames, etc
source $DIR/.secrets

BACKUP_FILE="homeassistant.tar.gz"
HASSIO_DB_USER=$SECRETS_HASSIO_DB_USER
HASSIO_DB_PWD=$SECRETS_HASSIO_DB_PWD
NAS_USER="telepathic"
NAS_HOST="apollo"

DATE=`date +%Y-%m-%d`

# Create MySQL DB dump of Home Assistant
printf "${COLOR_YELLOW}Taking a dump...\n${COLOR_NORMAL}"
mysqldump --user=$HASSIO_DB_USER --password=$HASSIO_DB_PWD --default-character-set=utf8 "home_assistant" > /backup/homeassistant-$DATE.sql
printf "${COLOR_GREEN}Dump finished!\n${COLOR_NORMAL}"

# Make use of the hassio-remote-backup file to bundle everything up nicely
# (https://github.com/casenjo/hassio-remote-backup)
printf "${COLOR_YELLOW}Making a bundle...\n${COLOR_NORMAL}"
tar cvf - /backup | gzip -9 - > /tmp/homeassistant.tar.gz
printf "${COLOR_GREEN}Bundle finished!\n${COLOR_NORMAL}"

# rsync to the NAS


# Sync!
#rsync -az $HASSIO_USER@$HASSIO_HOST:/config/ $HASSIO_NEW_BACKUP_FOLDER_PATH/

printf "${COLOR_GREEN}Backup finished :)\n${COLOR_NORMAL}"
